### PR TITLE
PR by PaLoALo and Arkangel5736

### PR DESCRIPTION
**Pull request by PaloAlo**
[WhiteRiverToC_PaLoALo and Arkangel5736.zip](https://github.com/user-attachments/files/16605972/WhiteRiverToC_PaLoALo.and.Arkangel5736.zip)

all the files EXCEPT for kuvas, pavlichenkos, and the main required folder are revised and seemingly working. All files will need to be tested thoroughly to make sure all aspects are working correctly. I was far from that point imho.

1) kuvas still needs a lot of testing since all the apparel was removed in V1.0 i have amended it to work. however its unclear if kuvas ever worked correctly since the quest for the red armor seems to be borked. i 'think' i have fixed it, but won't know till i spend some time trying to work it through. zero errors so far.

2) pavlichenkos i noticed there was an abandoned idea to add a quest and treasure map for a 8x scope, so i have i 'think' added that in so it works. needs testing but zero errors so far.

3) the main required file needs a major overhaul. names have changed, as has the entire quest and challenge system in the game. 
I'm still working on trying to get the 3 quests to show in the traders dialog AND also have the quests show a marker to return to the trader properly. Also, it looks like the random elite crate item never worked? it had an empty loot entry so i have written an entire setup for that, but it still needs testing.

i have NOT included the three files mentioned above for these reasons. Either you fix them, or i do, or we collaborate, but i am not confident enough to provide them as is till i do some more work on them.
Also, I did remove a lot of the comments in the files mostly because i find it difficult to read through with so much 'branding' and commentary.

### CODE REVIEW

**Comment by XelaNull** [comment]
Thank you very much. I've got the zip file downloaded and will towards committing it into this branch on your behalf. I don't mind doing this (you are contributing!), but did want to point out to you the normal process would be you making changes in this branch yourself. In this case, you'd take your modified files and you'd push them up into this branch via git commit process. This way the modifications to the files come tagged with your name(s). Because I'll push these changes in to the GIT repo, they are going to show my name on it instead of yours. It's no big deal to me, but it does mean less visibility into changes that you've contributed on. I did at least want to point this out to you in case you didn't know this or weren't sure. Mac & Linux makes this process far easier than Windows. It Is possible to get VS Code on Windows working, but the native GIT support is not great.

I'm not sure what kind of code editor you use, but I use VS Code which is free and can do excellent syntax highlighting of comments. I'll probably end up selectively taking your code changes and keeping comments since I use them to keep my own sanity over the code and remind myself what its for.

You are right that the base quest needs probably a near complete overhaul. I'll spend my time toying around with this tonight to what I can come up with. As you know, this quest is the one that ties all of the others together, so while Kuva could be left out of next release if its found to be broken.. this required modlet most definitely has to be working properly for the entire pack to be playable.

**Comment by XelaNull** [comment]
On Kuva and Pavlichenko, please focus your efforts there while I look to merge your changes and look over this core required modlet and formulate plan. This way we are splitting our efforts and tag-teaming the remaining modifications.

For what its worth, this modpack (ToC) I have the most invested in. And while I have nearly 60 modlets to work through updating for v1.0.. this set is by far most important to me and will see my time coding time until we have this to playable release.

**Comment by XelaNull** [comment]
I took cursory glance at what you've provided and have to say I'm blown away by the number of changes you've made. A lot of this is code cleanup. It looks like you even made corrections to localization.  On first glance this looks really fantastic, and also is going to take me some time to sort through. Clearly, you two have invested a lot of time into this. Thank you

**Comment by PaloAlo** [comment]
hi again. you had a lot of comments and questions, so i will give you some background. 

i have been running a heavily modded Valheim server for about 3 years now. that was my first dedicated server setup, and i still have it running. i guess before that i got into modding my games with Skyrim. Now im kinda over valheim at this point, so i had decided to setup a 7dtd server. however my friends quickly got bored but i really like the simplicity of the xml schema and how easy it is to get into modding the game.

for the last year i have been making mods, this is my profile on nexus. 
https://next.nexusmods.com/profile/PaLoALo/about-me

i saw arkangel asking for someone to resurrect ToC on discord, and i remember this mod (although i only started playing 7dtd in A20) and it didnt work then lol, but i wanted to see if i could get it working with what i know now. so i got together with him and gave it a try. he's really good at testing and coming up with ideas so together we worked well. 

anyway, yes we put in a lot of effort and it paid off. as i mentioned, i would like credit for both of us helping, but my main goal is to make this mod available again to the community so others can enjoy it.

**Comment by PaloAlo** [comment]
a lot of the 'code cleanup' was necessary bc so much has changed since A19 to now. the zeds, vehicles, weapons, all had changed and needed the code updated from scratch. but that was mostly a lot of copy/paste and making sure that things didnt get lost in the mix.

as for the modlets that had parts that didnt work, well that required re-writing.

**Comment by XelaNull** [comment]
I'd love to connect with you on Discord if you are open to it. I'm on the 7DTD official discord server as ShoudenKalferas. I've been accused of enjoying modding more than playing, but my 1600hrs playing 7DTD probably is a testament to how much I also enjoy the game. :) I also love Valheim and have even recently run a heavily modded server. I've got a dedicated server I pay for, for my family's usage which also doubles as a gameserver running out of a datacenter. I updated this modpack for about 4 years before I trailed off in 2022 to move onto other things. I've been through so many major release changes (A16->A17, A17->A18, etc) over those years I really got worn down fixing my *many* modlets every time they'd change the smallest thing. Some major releases were horrific on all modlet authors. This was all pre-release though. I've got a docker container server mod manager that runs web server and the game server side-by-side that gives me web interface to manage all the mods loaded on the server. I have a collection pack that I maintained for awhile called [Neopolitan](https://7daystodiemods.com/neopolitan-collection-mod/) where I collected together all the best mods(IMO), used AI to set up localization files for all of them (this was back before ChatGPT when Watson was most viable way to do it), and then released it as a singular either monolithic or broken out pack. The entire collection pack was somewhere around 100 modlets if I recall correctly.

I'd love to compare notes on what modlets you have running as I most definitely intend to get the collection pack Neopolitan updated for 1.0 after I'm done working to get this Tools of Citizenship updated.

I'm still getting back into it and as you mentioned, a lot has changed. Even the challenge system is brand new to me. I did do a deep dive last night on the vanilla challenges.xml and quests.xml to familiarize myself with the changes they've made. For example, killing a zombie can no longer be an objective to a quest. Instead, it was moved to challenges. Also, I see Taza's quest was changed to no longer require holding the axe while killing.. presumably because of same reason. It's possible maybe there might be a way to set it back up using a challenge as challenges support Z kills. But offhand I did not see a way to ensure someone is holding an item while the objective is being completed for the challenge.

Last night I got a new challenges UI page set up, with one row representing each of the three citizenship levels. I'm loosely thinking that at minimum the citizenship cards could be handed out upon success of completing a set of challenges. I haven't yet looked at trader interaction yet on this. I'll work tonight on fleshing out this idea a bit more and maybe get over to a trader to see if I can toy a bit with interactions. At the moment, I don't see a reason to change up the citizenship card as an entrypoint/doorway to reach the other quests. I will try as hard as I can on this detail as it is key to not have to completely redesign how the other quests tie into it.

**Comment by PaloAlo** [comment]
I can VC anytime now for next couple hours. I'm north america west coast
time zone.
If not tonight any evening is good for me.

**Comment by XelaNull** [comment]
Please give me some time to get back into things. At the moment, I'm still feeling like I'm riding around with training wheels re-learning the language. Amazing how fast my brain shoves knowledge out to make room for new things. :) I joke to my wife that being a coder is like being a college professor with a long whiteboard with notes scratched all over it. It takes time to fill the whiteboard in and very easy to erase stuff. I'm East Coast.

In the meantime, would love to connect with you & arkangel5736 over Discord. I found arkangel5736 on Discord and messaged them but they have not replied. I wasn't able to find you by your name PaLoALo. Please add me as friend. You can find me on 7DTD Official Discord server under name ShoudenKalferas.

I'm thinking of taking the core required modlet in a different direction than in the past. I had been waiting for 1.0 release for so long figuring that once 1.0 came out, they would stop making as many changes to underlying XPath/XML. Now that 1.0 is out, its easier to lay a foundation that should work better into the future and provide better player experience. 

At the moment, I've just been writing it up in a text document and looking for logic flaws or loopholes. I also crafted my wife a basic required modlet with just the citizenship cards and nothing else, so that she could take the .zip file you provided and start working her way through testing each of the quests one by one (via buildcreate + pulling citizenship cards out directly).

**Review by XelaNull — APPROVED** [review]
A lot of hard work went into this release by ALo, Arkangel, and myself. But nearly all of the credit for this release goes to ALo and Arkangel. Without their help, I'd likely still be in the weeds fixing modlets.

**Pull request merged**
